# Generated by Django 5.1.7 on 2025-04-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
