# Generated by Django 5.1.7 on 2025-04-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_habitcompletion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitcompletion',
            name='streak_length',
        ),
    ]
